import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Providers from './providers'
import LayoutWithNavbar from '../components/LayoutWithNavbar'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Pledge & Grow',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          <LayoutWithNavbar>{children}</LayoutWithNavbar>
        </Providers>
      </body>
    </html>
  )
}
